const responseData = {
  shopName: "fewfwe",
  productCategory: "fewfwefw",
  productTitle: "Bhadohi Carpets",
  pricing: "423423",
  quantity: "151",
  productDescription: "bhadohi carpets",
  productVariation: "bhadohi carpets",
  response: {
    ProductRegionalNames: [
      "Bhadohi Carpets",
      "Bhadohi Rugs",
      "Bhadohi Kaaleen",
    ],
    ProductName: "Bhadohi Carpets",
    ProductDescription:
      "Bhadohi Carpets are meticulously crafted hand-woven and machine-made carpets from the Bhadohi region of Uttar Pradesh, India. Known for their intricate designs and superior quality, these carpets bring an element of elegance and timeless beauty to any space. Made from soft acrylic wool, they are durable, stain-resistant, and available in various sizes and colors to match diverse interior decor styles.",
    ProductVariation: "Bhadohi Carpets",
    AboutProduct: [
      "Manufactured in Bhadohi, Uttar Pradesh, known as India's Carpet City.",
      "Available in multiple sizes and colors to suit different decor needs.",
      "Made from high-quality soft acrylic wool for a plush feel.",
      "Features hand-embossed designs for added elegance.",
      "Durable and long-lasting with high pile thickness.",
      "Stain-resistant and easy to clean, suitable for both indoor and outdoor use.",
      "Anti-slip backing ensures safety for children and the elderly.",
      "Ideal for living rooms, bedrooms, offices, and halls.",
      "Available with EMI options for easy purchase.",
      "Highly rated for quality, appearance, and value for money.",
    ],
    ProductTagline: "Bhadohi Carpets: Weaving Elegance into Every Step",
    ProductPrompt:
      "Transform your interior spaces with Bhadohi Carpets. Capture the intricate designs and plush textures in professional photos that highlight the elegance and durability of each piece. Use proper lighting and angles to showcase the vibrant colors and high pile thickness, ensuring your ecommerce listings attract and convert potential buyers.",
    MarketPainPoints: [
      "High competition from other carpet manufacturers.",
      "Need for maintaining consistent quality across batches.",
      "Logistics and shipping challenges for heavy and bulky items.",
      "Customer hesitation in purchasing high-value items online without tactile experience.",
    ],
    CustomerAcquisition: [
      "Utilize social media platforms to showcase the craftsmanship and uniqueness of Bhadohi Carpets.",
      "Collaborate with interior designers and home decor influencers for endorsements.",
      "Offer limited-time discounts and EMI options to attract budget-conscious buyers.",
      "Implement a referral program to encourage word-of-mouth marketing.",
    ],
    MarketEntryStrategy: [
      "Establish partnerships with online marketplaces like Amazon and Flipkart.",
      "Develop a user-friendly website with detailed product descriptions and high-quality images.",
      "Invest in SEO and PPC campaigns to drive traffic to the website.",
      "Attend home decor and interior design exhibitions to increase brand visibility.",
    ],
    SeoFriendlyTags: [
      "Bhadohi Carpets",
      "Handwoven Rugs",
      "Indian Carpets",
      "Soft Acrylic Wool Carpets",
      "Stain Resistant Rugs",
      "High Pile Carpets",
      "Indoor Outdoor Carpets",
      "Luxurious Area Rugs",
      "Traditional Indian Rugs",
      "Anti-slip Carpets",
    ],
    newImages: [],
  },
  images: [],
  prompt:
    "Please change the background of the input Image such that they are Ecommerce ready. The product is called Bhadohi Carpets",
  uid: "66d401809103a5b67d78ab42",
};

const responseData2 = {
  inputLanguage: "english",
  shopName: "",
  sellerState: "",
  productlanguage: "",
  productCategory: "",
  productTitle: "fefew",
  pricing: "fwefwe432",
  productDescription: "fwefwefwe",
  productVariation: "fwefwefwe",
  response: {
    ProductRegionalNames: [
      "फ़ेफ़ेव (Hindi)",
      "ఫెఫెవ్ (Telugu)",
      "ಫೆಫೆವ್ (Kannada)",
      "ഫെഫെവ് (Malayalam)",
      "ஃபெஃபெவ் (Tamil)",
      "ಫೆಫೆವ್ (Marathi)",
    ],
    ProductName: "Fefew",
    ProductDescription:
      "Fefew is a versatile product designed to meet a variety of needs with its unique features and high-quality build. It offers users a reliable and efficient solution, making it a preferred choice in its category.",
    ProductVariation:
      "Available in multiple variations including size, color, and material to suit different preferences and requirements.",
    AboutProduct: [
      "High-quality build ensuring durability and reliability.",
      "Available in multiple sizes to cater to different user needs.",
      "Offers various color options to match user preferences.",
      "Made from premium materials for enhanced performance.",
      "Easy to use with a user-friendly design.",
      "Affordable pricing offering great value for money.",
      "Ideal for both personal and professional use.",
      "Widely available across different regions in India.",
      "Positive customer reviews and high ratings.",
      "Backed by excellent customer support.",
    ],
    ProductTagline: "Fefew - Your Reliable Companion for Every Need",
    ProductPrompt:
      "Transform your photos into stunning professional images with Fefew. Simply upload your photos, and let Fefew work its magic to enhance details, adjust lighting, and ensure your images look perfect for ecommerce use.",
    MarketPainPoints: [
      "High competition in the market.",
      "Customer skepticism about product quality.",
      "Price sensitivity among potential buyers.",
      "Limited brand awareness in certain regions.",
    ],
    CustomerAcquisition: [
      "Leverage social media platforms for targeted advertising.",
      "Offer introductory discounts and promotions.",
      "Collaborate with influencers for product endorsements.",
      "Provide high-quality content and tutorials to educate customers.",
    ],
    MarketEntryStrategy: [
      "Conduct market research to understand customer needs and preferences.",
      "Develop a strong online presence with an easy-to-navigate website.",
      "Utilize SEO strategies to improve search engine rankings.",
      "Build partnerships with local retailers for wider distribution.",
    ],
    SeoFriendlyTags: [
      "Fefew",
      "High-quality product",
      "Reliable solution",
      "Affordable pricing",
      "Multiple variations",
      "Customer-friendly",
      "Premium materials",
      "Ecommerce photos",
      "Professional images",
      "India",
    ],
    newImages: [],
  },
  companyLogo: "",
  images: [],
  prompt:
    "Please change the background of the input Image such that they are Ecommerce ready. The product is called fefew",
};

const responseData3 = {
  inputLanguage: "english",
  shopName: "Ajay shop",
  sellerState: "",
  productlanguage: "NElgish",
  productCategory: "Textile",
  productTitle: "Earthen Water bottle",
  pricing: "12000",
  quantity: "124",
  productDescription:
    "Stay refreshed and eco-conscious with this beautifully handcrafted Earthen Water Bottle. Made from natural clay, this bottle is designed to keep your water cool while retaining the earthy freshness that comes from drinking from clay. The porous nature of the earthen material ensures natural cooling, offering a refreshing experience even on the hottest days.\n",
  productVariation:
    "\t1.\tClassic Earthen Bottle:\n\t•\tCapacity: 1L\n\t•\tFeatures: Natural cooling, simple design.\n\t2.\tBottle with Matching Cup:\n\t•\tCapacity: 1L + 200ml cup\n\t•\tFeatures: Great for serving with style.\n\t3.\tHand-Painted Bottle:\n\t•\tCapacity: 1L\n\t•\tFeatures: Decorative, artistic touch.\n\t4.\tInsulated Earthen Bottle:\n\t•\tCapacity: 1L\n\t•\tFeatures: Insulated sleeve for extra cooling.\n\t5.\tPersonalized Bottle:\n\t•\tCapacity: 1L\n\t•\tFeatures: Custom engraving for names or quotes.",
  response: {
    ProductRegionalNames: [
      "Mitti Ki Bottle",
      "Matka Bottle",
      "Kudam Bottles",
      "Mann Pot",
      "Chatti Bottle",
    ],
    ProductName: "Earthen Water Bottle",
    ProductDescription:
      "Stay refreshed and eco-conscious with our beautifully handcrafted Earthen Water Bottle. Made from natural clay, this bottle is designed to keep your water cool while retaining the earthy freshness that comes from drinking from clay. The porous nature of the earthen material ensures natural cooling, offering a refreshing experience even on the hottest days.",
    ProductVariation: [
      {
        VariationName: "Classic Earthen Bottle",
        Capacity: "1L",
        Features: ["Natural cooling", "Simple design"],
      },
      {
        VariationName: "Bottle with Matching Cup",
        Capacity: "1L + 200ml cup",
        Features: ["Great for serving with style"],
      },
      {
        VariationName: "Hand-Painted Bottle",
        Capacity: "1L",
        Features: ["Decorative", "Artistic touch"],
      },
      {
        VariationName: "Insulated Earthen Bottle",
        Capacity: "1L",
        Features: ["Insulated sleeve for extra cooling"],
      },
      {
        VariationName: "Personalized Bottle",
        Capacity: "1L",
        Features: ["Custom engraving for names or quotes"],
      },
    ],
    AboutProduct: [
      "Eco-friendly and handmade using 100% natural clay.",
      "Provides natural cooling due to the porous nature of clay.",
      "Easy to clean and refill.",
      "Enhances the taste of water by adding a unique earthy flavor.",
      "Health benefits include balancing pH levels and boosting metabolism.",
      "Soothes the throat and prevents sunstrokes.",
      "Durable and aesthetic with variations available.",
      "Free from harmful chemicals, non-toxic, and unglazed.",
      "Promotes traditional and sustainable lifestyle choices.",
      "Cost-effective and provides value for money.",
    ],
    ProductTagline: "Naturally Cool, Purely Refreshing.",
    ProductPrompt:
      "Transform your product photos into professional e-commerce images by showcasing the elegant design and natural cooling benefits of our Earthen Water Bottles. Highlight the handcrafted details and unique variations for an appealing presentation.",
    MarketPainPoints: [
      "Lack of awareness about the health benefits of clay water bottles.",
      "Competition from modern water bottles and other eco-friendly options.",
      "Perceived difficulty in maintenance and cleaning.",
      "Higher price point compared to plastic and metal bottles.",
      "Limited availability in mainstream retail stores.",
    ],
    CustomerAcquisition: [
      "Leverage social media platforms to educate and engage potential customers.",
      "Collaborate with eco-friendly influencers for product endorsements.",
      "Offer discounts and combo deals to attract cost-conscious buyers.",
      "Participate in eco-friendly fairs and events to increase brand visibility.",
      "Implement a referral program to encourage word-of-mouth marketing.",
    ],
    MarketEntryStrategy: [
      "Start with an online presence through a dedicated website and major e-commerce platforms.",
      "Target eco-conscious consumers with focused advertising on sustainability.",
    ],
    SeoFriendlyTags: [
      "Clay Water Bottle",
      "Earthen Water Bottle",
      "Natural Cooling Bottle",
      "Eco-Friendly Water Bottle",
      "Handmade Clay Bottle",
      "Mitti Water Bottle",
      "Terracotta Water Bottle",
      "Healthy Drinking Bottle",
      "Traditional Water Bottle",
      "Sustainable Water Bottle",
    ],
    newImages: [null, null, null],
  },
  companyLogo: "",
  images: [
    "https://vyaparbackend.s3.amazonaws.com/uploads/image3.jpg",
    "https://vyaparbackend.s3.amazonaws.com/uploads/image2.jpeg",
    "https://vyaparbackend.s3.amazonaws.com/uploads/img1.jpg",
  ],
  prompt:
    "Please change the background of the input Image such that they are Ecommerce ready. The product is called Earthen Water bottle",
};



const storeData = {
    name:productData.response.ProductName,
    category:productData.ProductCategory,
    pricing:productData.pricing,
    quantity:productData.quantity,
    tagline:productData.response.ProductTagline,
    description:productData.response.ProductDescription,
    variation:productData.response.ProductVariation,
    images:productData.images.map((image)=> {return `https://image-api.photoroom.com/v2/edit?background.prompt=${productData.prompt}&background.seed=42&outputSize=1000x1000&padding=0.1&imageUrl=${image}&apiKey=${photoroomApi}`}),
    about:productData.response.AboutProduct,
    marketPainPoints:productData.response.MarketPainPoints,
    customerAcquisition:productData.response.CustomerAcquisition,
    marketEntryStrategy:productData.response.MarketEntryStrategy,
    seoFriendlyTags:productData.response.SeoFriendlyTags,
    regionalNames:productData.response.ProductRegionalNames,
}